#ifndef _WINO_HW_CONFIG_H_
#define _WINO_HW_CONFIG_H_
#define WINO_DOMAIN_SIZE 4
#define INPUT_BUFFER_DEPTH_BITWIDTH 12
#define OUTPUT_BUFFER_DEPTH_BITWIDTH 10
#define WEIGHT_BUFFER_DEPTH_BITWIDTH 10
#define WINO_HEIGHT 1
#define WINO_WIDTH 1
#define INBUFFER_HEIGHT_BITWIDTH 3
#define INDEPTH_MINITILE_SIZE_BITWIDTH 0
#define WINO_W2 1
#define WINO_H2 1
#endif
